import 'package:dio/dio.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:field_visit_app/presentation/providers/auth_api_provider.dart';
import 'package:field_visit_app/presentation/providers/auth_provider.dart';

class AccountScreen extends ConsumerStatefulWidget { const AccountScreen({super.key}); @override ConsumerState<AccountScreen> createState() => _AccountState(); }
class _AccountState extends ConsumerState<AccountScreen> {
  final first = TextEditingController(); final last = TextEditingController(); final mobile = TextEditingController(); final current = TextEditingController(); final password = TextEditingController(); final confirm = TextEditingController();
  @override void initState() { super.initState(); final user = ref.read(authProvider).valueOrNull; first.text = user?.fullName ?? ''; }
  @override void dispose() { first.dispose(); last.dispose(); mobile.dispose(); current.dispose(); password.dispose(); confirm.dispose(); super.dispose(); }
  Future<void> profile() async { try { await ref.read(authApiProvider).updateProfile({'first_name': first.text.trim(), 'last_name': last.text.trim(), 'mobile': mobile.text.trim()}); await ref.read(authProvider.notifier).getProfile(); if (mounted) ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('Profile updated'))); } catch (e) { _show(e); } }
  Future<void> changePassword() async { if (password.text.length < 8 || password.text != confirm.text) { _show('Password must be 8+ characters and match'); return; } try { await ref.read(authApiProvider).changePassword({'current_password': current.text, 'password': password.text, 'password_confirmation': confirm.text}); current.clear(); password.clear(); confirm.clear(); if (mounted) ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('Password changed'))); } catch (e) { _show(e); } }
  void _show(Object e) { if (mounted) ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text(e is DioException && e.response?.data is Map ? ((e.response!.data as Map)['message'] ?? (e.response!.data as Map)['errors']).toString() : e.toString()))); }
  @override Widget build(BuildContext context) => Scaffold(appBar: AppBar(title: const Text('My account')), body: ListView(padding: const EdgeInsets.all(16), children: [const Text('Profile', style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold)), TextField(controller: first, decoration: const InputDecoration(labelText: 'First name')), TextField(controller: last, decoration: const InputDecoration(labelText: 'Last name')), TextField(controller: mobile, decoration: const InputDecoration(labelText: 'Mobile')), const SizedBox(height: 12), FilledButton(onPressed: profile, child: const Text('Update profile')), const Divider(height: 36), const Text('Change password', style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold)), TextField(controller: current, obscureText: true, decoration: const InputDecoration(labelText: 'Current password')), TextField(controller: password, obscureText: true, decoration: const InputDecoration(labelText: 'New password')), TextField(controller: confirm, obscureText: true, decoration: const InputDecoration(labelText: 'Confirm new password')), const SizedBox(height: 12), FilledButton(onPressed: changePassword, child: const Text('Change password'))]));
}
