import 'package:dio/dio.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:field_visit_app/presentation/providers/assignments_provider.dart';
import 'package:field_visit_app/presentation/providers/outlets_provider.dart';

class AssignmentsScreen extends ConsumerWidget {
  const AssignmentsScreen({super.key});
  @override Widget build(BuildContext context, WidgetRef ref) { final state = ref.watch(assignmentsProvider); return Scaffold(appBar: AppBar(title: const Text('Outlet assignments')), body: RefreshIndicator(onRefresh: ref.read(assignmentsProvider.notifier).fetch, child: state.when(loading: () => const Center(child: CircularProgressIndicator()), error: (e, _) => Center(child: Text(_message(e))), data: (items) => items.isEmpty ? ListView(children: const [SizedBox(height: 220), Center(child: Text('No assignments found'))]) : ListView.builder(padding: const EdgeInsets.all(12), itemCount: items.length, itemBuilder: (_, i) { final item = items[i]; return Card(child: ListTile(leading: const Icon(Icons.person_pin), title: Text('Outlet #${item['outlet_id']}'), subtitle: Text('User #${item['user_id']}  •  ${item['status'] ?? ''}'), trailing: IconButton(icon: const Icon(Icons.delete_outline), onPressed: () => ref.read(assignmentsProvider.notifier).remove((item['id'] as num).toInt())))); }))), floatingActionButton: FloatingActionButton(onPressed: () => _create(context, ref), child: const Icon(Icons.add))); }
}

Future<void> _create(BuildContext context, WidgetRef ref) async { final outlets = ref.read(outletsProvider).valueOrNull ?? const []; if (outlets.isEmpty) { ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('Create an outlet first'))); return; } final user = TextEditingController(); int outletId = outlets.first.id; await showDialog<void>(context: context, builder: (dialogContext) => StatefulBuilder(builder: (context, setState) => AlertDialog(title: const Text('Assign outlet'), content: Column(mainAxisSize: MainAxisSize.min, children: [DropdownButtonFormField<int>(value: outletId, items: outlets.map((o) => DropdownMenuItem(value: o.id, child: Text(o.name))).toList(), onChanged: (v) => setState(() => outletId = v ?? outletId), decoration: const InputDecoration(labelText: 'Outlet')), TextField(controller: user, keyboardType: TextInputType.number, decoration: const InputDecoration(labelText: 'User ID'))]), actions: [TextButton(onPressed: () => Navigator.pop(dialogContext), child: const Text('Cancel')), FilledButton(onPressed: () async { final userId = int.tryParse(user.text); if (userId == null) return; try { await ref.read(assignmentsProvider.notifier).save({'outlet_id': outletId, 'user_id': userId}, null); if (dialogContext.mounted) Navigator.pop(dialogContext); } catch (e) { if (dialogContext.mounted) ScaffoldMessenger.of(dialogContext).showSnackBar(SnackBar(content: Text(_message(e)))); } }, child: const Text('Assign'))]))); user.dispose(); }
String _message(Object e) => e is DioException && e.response?.data is Map ? ((e.response!.data as Map)['message'] ?? (e.response!.data as Map)['errors'] ?? e.message).toString() : e.toString();
