import 'package:dio/dio.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:field_visit_app/presentation/providers/auth_settings_provider.dart';

class AuthSettingsScreen extends ConsumerStatefulWidget { const AuthSettingsScreen({super.key}); @override ConsumerState<AuthSettingsScreen> createState() => _AuthSettingsState(); }
class _AuthSettingsState extends ConsumerState<AuthSettingsScreen> with SingleTickerProviderStateMixin { late final TabController tabs = TabController(length: 2, vsync: this); @override void dispose() { tabs.dispose(); super.dispose(); } @override Widget build(BuildContext context) => Scaffold(appBar: AppBar(title: const Text('Auth settings'), bottom: TabBar(controller: tabs, tabs: const [Tab(text: 'Roles'), Tab(text: 'Permissions')])), body: TabBarView(controller: tabs, children: const [_RolesList(), _PermissionsList()])); }

class _RolesList extends ConsumerWidget { const _RolesList(); @override Widget build(BuildContext context, WidgetRef ref) { final state = ref.watch(rolesProvider); final notifier = ref.read(rolesProvider.notifier); return Scaffold(body: RefreshIndicator(onRefresh: notifier.fetch, child: state.when(loading: () => const Center(child: CircularProgressIndicator()), error: (e, _) => Center(child: Text(_message(e))), data: (items) => items.isEmpty ? ListView(children: const [SizedBox(height: 220), Center(child: Text('No roles found'))]) : ListView.builder(padding: const EdgeInsets.all(12), itemCount: items.length, itemBuilder: (_, i) { final item = items[i]; final id = (item['id'] as num).toInt(); return Card(child: ListTile(leading: const Icon(Icons.admin_panel_settings), title: Text('${item['name'] ?? ''}'), subtitle: Text('${item['guard_name'] ?? 'api'}  •  ${item['status'] ?? ''}'), onTap: () => _roleForm(context, ref, item), trailing: PopupMenuButton<String>(onSelected: (action) async { try { if (action == 'toggle') await notifier.toggle(id); else if (action == 'delete') await notifier.remove(id); } catch (e) { if (context.mounted) ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text(_message(e)))); } }, itemBuilder: (_) => const [PopupMenuItem(value: 'toggle', child: Text('Toggle status')), PopupMenuItem(value: 'delete', child: Text('Delete'))]))); }))), floatingActionButton: FloatingActionButton(heroTag: 'roles_add', onPressed: () => _roleForm(context, ref, null), child: const Icon(Icons.add))); } }

class _PermissionsList extends ConsumerWidget { const _PermissionsList(); @override Widget build(BuildContext context, WidgetRef ref) { final state = ref.watch(permissionsProvider); return Scaffold(body: RefreshIndicator(onRefresh: ref.read(permissionsProvider.notifier).fetch, child: state.when(loading: () => const Center(child: CircularProgressIndicator()), error: (e, _) => Center(child: Text(_message(e))), data: (items) => items.isEmpty ? ListView(children: const [SizedBox(height: 220), Center(child: Text('No permissions found'))]) : ListView.builder(padding: const EdgeInsets.all(12), itemCount: items.length, itemBuilder: (_, i) { final item = items[i]; return ListTile(leading: const Icon(Icons.key), title: Text('${item['title'] ?? item['name'] ?? ''}'), subtitle: Text('${item['name'] ?? ''}  •  ${item['guard_name'] ?? ''}')); }))), ); } }

Future<void> _roleForm(BuildContext context, WidgetRef ref, Map<String, dynamic>? item) async { final name = TextEditingController(text: item?['name']?.toString()); final guard = TextEditingController(text: item?['guard_name']?.toString() ?? 'api'); await showDialog<void>(context: context, builder: (dialogContext) => AlertDialog(title: Text('${item == null ? 'Add' : 'Edit'} role'), content: Column(mainAxisSize: MainAxisSize.min, children: [TextField(controller: name, decoration: const InputDecoration(labelText: 'Name')), TextField(controller: guard, decoration: const InputDecoration(labelText: 'Guard name'))]), actions: [TextButton(onPressed: () => Navigator.pop(dialogContext), child: const Text('Cancel')), FilledButton(onPressed: () async { if (name.text.trim().isEmpty) { if (dialogContext.mounted) ScaffoldMessenger.of(dialogContext).showSnackBar(const SnackBar(content: Text('Role name is required'))); return; } try { await ref.read(rolesProvider.notifier).save({'name': name.text.trim(), 'guard_name': guard.text.trim(), 'status': 1}, (item?['id'] as num?)?.toInt()); if (dialogContext.mounted) Navigator.pop(dialogContext); } catch (e) { if (dialogContext.mounted) ScaffoldMessenger.of(dialogContext).showSnackBar(SnackBar(content: Text(_message(e)))); } }, child: const Text('Save'))])); name.dispose(); guard.dispose(); }
String _message(Object e) => e is DioException && e.response?.data is Map ? ((e.response!.data as Map)['message'] ?? (e.response!.data as Map)['errors'] ?? e.message).toString() : e.toString();
