import 'package:dio/dio.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:field_visit_app/presentation/providers/directory_provider.dart';

class DirectoryScreen extends ConsumerStatefulWidget { const DirectoryScreen({super.key}); @override ConsumerState<DirectoryScreen> createState() => _DirectoryState(); }
class _DirectoryState extends ConsumerState<DirectoryScreen> with SingleTickerProviderStateMixin { late final TabController tabs = TabController(length: 2, vsync: this); @override void dispose() { tabs.dispose(); super.dispose(); } @override Widget build(BuildContext context) => Scaffold(appBar: AppBar(title: const Text('Directory'), bottom: TabBar(controller: tabs, tabs: const [Tab(text: 'Users'), Tab(text: 'Companies')])), body: TabBarView(controller: tabs, children: const [_DirectoryList(users: true), _DirectoryList(users: false)])); }

class _DirectoryList extends ConsumerWidget { final bool users; const _DirectoryList({required this.users}); @override Widget build(BuildContext context, WidgetRef ref) { final provider = users ? usersProvider : companiesProvider; final state = ref.watch(provider); final notifier = ref.read(provider.notifier); return Scaffold(body: RefreshIndicator(onRefresh: notifier.fetch, child: state.when(loading: () => const Center(child: CircularProgressIndicator()), error: (e, _) => Center(child: Text(_message(e))), data: (items) => items.isEmpty ? ListView(children: const [SizedBox(height: 220), Center(child: Text('No records found'))]) : ListView.builder(padding: const EdgeInsets.all(12), itemCount: items.length, itemBuilder: (_, i) { final item = items[i]; final id = (item['id'] as num).toInt(); return Card(child: ListTile(leading: Icon(users ? Icons.person : Icons.business), title: Text(users ? '${item['full_name'] ?? item['first_name'] ?? ''}' : '${item['name'] ?? ''}'), subtitle: Text(users ? '${item['email'] ?? ''}  •  ${item['status'] ?? ''}' : '${item['slug'] ?? ''}  •  ${item['status'] ?? ''}'), onTap: () => _form(context, ref, users, item), trailing: PopupMenuButton<String>(onSelected: (action) async { try { if (action == 'toggle' && users) await notifier.toggle(id); if (action == 'delete') await notifier.remove(id); } catch (e) { if (context.mounted) ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text(_message(e)))); } }, itemBuilder: (_) => [if (users) const PopupMenuItem(value: 'toggle', child: Text('Toggle status')), const PopupMenuItem(value: 'delete', child: Text('Delete'))]))); }))), floatingActionButton: FloatingActionButton(onPressed: () => _form(context, ref, users, null), child: const Icon(Icons.add))); } }

Future<void> _form(BuildContext context, WidgetRef ref, bool users, Map<String, dynamic>? item) async { final first = TextEditingController(text: item?['first_name']?.toString() ?? item?['name']?.toString()); final last = TextEditingController(text: item?['last_name']?.toString()); final email = TextEditingController(text: item?['email']?.toString()); final slug = TextEditingController(text: item?['slug']?.toString()); final password = TextEditingController(); await showDialog<void>(context: context, builder: (dialogContext) => AlertDialog(title: Text('${item == null ? 'Add' : 'Edit'} ${users ? 'user' : 'company'}'), content: Column(mainAxisSize: MainAxisSize.min, children: [TextField(controller: first, decoration: InputDecoration(labelText: users ? 'First name' : 'Name')), if (users) TextField(controller: last, decoration: const InputDecoration(labelText: 'Last name')), if (users) TextField(controller: email, decoration: const InputDecoration(labelText: 'Email')), if (!users) TextField(controller: slug, decoration: const InputDecoration(labelText: 'Slug')), if (users && item == null) TextField(controller: password, obscureText: true, decoration: const InputDecoration(labelText: 'Password'))]), actions: [TextButton(onPressed: () => Navigator.pop(dialogContext), child: const Text('Cancel')), FilledButton(onPressed: () async { if (first.text.trim().isEmpty) return; final data = users ? <String, dynamic>{'first_name': first.text.trim(), 'last_name': last.text.trim(), 'email': email.text.trim(), if (item == null) 'password': password.text, if (item == null) 'password_confirmation': password.text} : <String, dynamic>{'name': first.text.trim(), 'slug': slug.text.trim()}; try { await ref.read((users ? usersProvider : companiesProvider).notifier).save(data, (item?['id'] as num?)?.toInt()); if (dialogContext.mounted) Navigator.pop(dialogContext); } catch (e) { if (dialogContext.mounted) ScaffoldMessenger.of(dialogContext).showSnackBar(SnackBar(content: Text(_message(e)))); } }, child: const Text('Save'))])); first.dispose(); last.dispose(); email.dispose(); slug.dispose(); password.dispose(); }
String _message(Object e) => e is DioException && e.response?.data is Map ? ((e.response!.data as Map)['message'] ?? (e.response!.data as Map)['errors'] ?? e.message).toString() : e.toString();
