import 'package:dio/dio.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:field_visit_app/presentation/providers/reference_data_provider.dart';

class ReferenceDataScreen extends ConsumerStatefulWidget { const ReferenceDataScreen({super.key}); @override ConsumerState<ReferenceDataScreen> createState() => _ReferenceDataState(); }
class _ReferenceDataState extends ConsumerState<ReferenceDataScreen> with SingleTickerProviderStateMixin { late final TabController tabs = TabController(length: 2, vsync: this); @override void dispose() { tabs.dispose(); super.dispose(); } @override Widget build(BuildContext context) => Scaffold(appBar: AppBar(title: const Text('Reference data'), bottom: TabBar(controller: tabs, tabs: const [Tab(text: 'Units'), Tab(text: 'Competitors')])), body: TabBarView(controller: tabs, children: const [_ReferenceList(units: true), _ReferenceList(units: false)])); }

class _ReferenceList extends ConsumerWidget { final bool units; const _ReferenceList({required this.units}); @override Widget build(BuildContext context, WidgetRef ref) { final provider = units ? unitsProvider : competitorsProvider; final state = ref.watch(provider); final notifier = ref.read(provider.notifier); return Scaffold(body: RefreshIndicator(onRefresh: notifier.fetch, child: state.when(loading: () => const Center(child: CircularProgressIndicator()), error: (e, _) => Center(child: Text(_message(e))), data: (items) => items.isEmpty ? ListView(children: const [SizedBox(height: 220), Center(child: Text('No records found'))]) : ListView.builder(padding: const EdgeInsets.all(12), itemCount: items.length, itemBuilder: (_, i) { final item = items[i]; return Card(child: ListTile(leading: Icon(units ? Icons.straighten : Icons.warning_amber), title: Text('${item['name'] ?? ''}'), subtitle: Text('${item['code'] ?? 'No code'}  •  ${item['status'] ?? ''}'), onTap: () => _edit(context, ref, units, item), trailing: IconButton(icon: const Icon(Icons.delete_outline), onPressed: () => notifier.remove((item['id'] as num).toInt())))); }))), floatingActionButton: FloatingActionButton(onPressed: () => _edit(context, ref, units, null), child: const Icon(Icons.add))); } }

Future<void> _edit(BuildContext context, WidgetRef ref, bool units, Map<String, dynamic>? item) async { final name = TextEditingController(text: item?['name']?.toString()); final code = TextEditingController(text: item?['code']?.toString()); final description = TextEditingController(text: item?['description']?.toString()); await showDialog<void>(context: context, builder: (dialogContext) => AlertDialog(title: Text('${item == null ? 'Add' : 'Edit'} ${units ? 'unit' : 'competitor'}'), content: Column(mainAxisSize: MainAxisSize.min, children: [TextField(controller: name, decoration: const InputDecoration(labelText: 'Name')), TextField(controller: code, decoration: const InputDecoration(labelText: 'Code')), if (!units) TextField(controller: description, decoration: const InputDecoration(labelText: 'Description'))]), actions: [TextButton(onPressed: () => Navigator.pop(dialogContext), child: const Text('Cancel')), FilledButton(onPressed: () async { if (name.text.trim().isEmpty) return; try { final provider = units ? unitsProvider : competitorsProvider; await ref.read(provider.notifier).save({'name': name.text.trim(), if (code.text.trim().isNotEmpty) 'code': code.text.trim(), if (!units && description.text.trim().isNotEmpty) 'description': description.text.trim()}, (item?['id'] as num?)?.toInt()); if (dialogContext.mounted) Navigator.pop(dialogContext); } catch (e) { if (dialogContext.mounted) ScaffoldMessenger.of(dialogContext).showSnackBar(SnackBar(content: Text(_message(e)))); } }, child: const Text('Save'))])); name.dispose(); code.dispose(); description.dispose(); }
String _message(Object e) => e is DioException && e.response?.data is Map ? ((e.response!.data as Map)['message'] ?? e.message).toString() : e.toString();
